### ISSUE TITLE
Remove the Border on the Iframe

### ISSUE THREAD

**Issue by DrewAllen88** [DrewAllen88/Enhancements#37]
Remove the border on the iframe in AEM.

[Example](author-prod2.www.marshinc.net/cf#/content/marsh/americas/us/en/client-segments/individuals-and-families/liability-coverage-estimator.html)

MAR-1370

**Comment by timproDev** [comment]
@DrewAllen88 FED complete | tested on local moz, safari, chrome, ie9, ipad, iphone | ready for further QA

**Comment by DrewAllen88** [comment]
Moving to production 8/14. Check production, Careers Taleo iframe, 8/17.

**Comment by DrewAllen88** [comment]
PROD done
