### ISSUE TITLE
Update Utility Nav

### ISSUE THREAD

**Issue by DrewAllen88** [DrewAllen88/Enhancements#38]
![image](https://cloud.githubusercontent.com/assets/8258720/8828883/53f0aace-3062-11e5-888f-20a7edf7c81e.png)
The anonymous state includes:
• Region Selector
• Language Selector
• Username/Email Field
• Password Field
• Login 
• Register 
• Search (new location on the right; new search button in blue)

![image](https://cloud.githubusercontent.com/assets/8258720/8828903/62a68dcc-3062-11e5-86b2-6180e624e5a4.png)
The logged in state includes:
• Region Selector
• Language Selector
• Link to Profile/Client Hub (new, consolidated with the below item into a drop down)
• Logout/Signout
• Search

**Comment by DrewAllen88** [comment]
[File in chatter](https://marsh.my.salesforce.com/06912000001gmxk?retUrl=%2Fchatter%2Fhandlers%2Flistview%2Ffile%3F_dc%3D1437507739870%26type%3Dfile%26filter%3Drecent%26fldr%3D%26linkDesc%3D%26customFilterParams%3D%26isSearchSupported%3D)

**Comment by joyjamir** [comment]
Update list above for BAU team to capture which items are new, which are being removed, etc.

**Comment by DrewAllen88** [comment]
@joyjamir Added some additional comments to the original and put some screenshots in for reference.

**Comment by DrewAllen88** [comment]
Related [ticket](https://github.com/DrewAllen88/Enhancements/issues/49).

**Comment by timproDev** [comment]
@DrewAllen88 Drew, I am looking through the PSD comps and do not seem to see any comps of the search field on mobile. FED would need these for the build. Any feedback on this?

**Comment by DrewAllen88** [comment]
Lance should be sending out PSDs for this once approved.

**Comment by timproDev** [comment]
@DrewAllen88 
FED complete
push to QA stage
further testing in required devices and browsers IE9 IE10 IE11 Safari, Firefox, Chrome, iPhone, iPad

**Comment by HarshitKhandelwal** [comment]
Can we have the updated HTML code and the CSS, JS files required for making the changes. Once changes incorporated, would test the other associated tickets as well.

**Comment by HarshitKhandelwal** [comment]
Dev complete

**Comment by DrewAllen88** [comment]
UAT Complete.
