### ISSUE TITLE
Utility Nav Breaking

### ISSUE THREAD

**Issue by DrewAllen88** [DrewAllen88/Enhancements#49]
Can be included in other utility nav update, reference [here](https://github.com/DrewAllen88/Enhancements/issues/38).
![image](https://cloud.githubusercontent.com/assets/8258720/8831792/bbd60566-3072-11e5-9df4-728ac95ca42c.png). 
Search and Logout are dropped from utility nav.
Keep in mind the design changes, that are being handled first.

**Comment by timproDev** [comment]
@DrewAllen88 FED complete | tested on local moz, safari, chrome, ie9, ipad, iphone | ready for further QA

**Comment by DrewAllen88** [comment]
Doesn't exist with new code/design.
