### ISSUE TITLE
Homepage Feature Area Updates

### ISSUE THREAD

**Issue by DrewAllen88** [DrewAllen88/Enhancements#55]
Requirements
- reduce the image height
- allow for multiple campaigns to be featured
- the user navigates between these multiple campaigns via the "bubbles"
- add help text to encourage character limit
- force the height of the image so that text will overflow if char limit is exceeded
- H1 and H2 tags should be switched and designs updated

Suggested character limits
- H2 - 65 - one line
- H1 - 70 - two lines
- body - 145 - two lines

[Here](https://marsh.my.salesforce.com/06912000001gnxM?retUrl=%2Fchatter%2Fhandlers%2Flistview%2Ffile%3F_dc%3D1438013304409%26type%3Dfile%26filter%3Drecent%26fldr%3D%26linkDesc%3D%26customFilterParams%3D%26isSearchSupported%3D) is a link to the PDF on Chatter showing the updated designs.

These images illustrate the change in H1 and H2 tags:
OLD
![image](https://cloud.githubusercontent.com/assets/8258720/8879279/8876d2d0-31fe-11e5-9345-53fcadcd4d6f.png)
NEW
![image](https://cloud.githubusercontent.com/assets/8258720/8879298/a5e5f210-31fe-11e5-951e-6878c0da97cd.png)

Related tickets:
https://github.com/DrewAllen88/Enhancements/issues/30, https://github.com/DrewAllen88/Enhancements/issues/29, https://github.com/DrewAllen88/Enhancements/issues/20, https://github.com/DrewAllen88/Enhancements/issues/24

**Comment by DrewAllen88** [comment]
Need to clarify the H1 and H2 tag changes. Check with Ian and Alvin about this.

**Comment by DrewAllen88** [comment]
Need to copy the promo carousel below the homepage image before the code is deployed to prod.

**Comment by timproDev** [comment]
The image dimensions pulled from the designs are as follows:
Desktop: width:1300px; height: 400px;
Tablet: width:780px; height: 400px;
Phone: width: 390px; height: 400px;

**Comment by monalishah** [comment]
Dev complete.

**Comment by DrewAllen88** [comment]
UAT complete.

On right click of component to edit, doesn't indicate what the component is:

![image](https://cloud.githubusercontent.com/assets/8258720/9580995/cd373e7a-4fca-11e5-9b28-689708ce775c.png)

**Comment by DrewAllen88** [comment]
Good.
