### ISSUE TITLE
Promo Carousel Updates

### ISSUE THREAD

**Issue by DrewAllen88** [DrewAllen88/Enhancements#56]
Requirements
- add help text on each of the fields to encourage character limits
- set the limit of entries to a maximum of 5
- add checkbox option to "open in new window"

Suggested character limits are as follows based on field names:
Title - two lines - 115 character limit (with spaces)
Description - three lines of text - 240 character limit (with spaces)

From [homepage](https://www.marsh.com/us/home.html):
![image](https://cloud.githubusercontent.com/assets/8258720/8991609/a58da7e0-36c7-11e5-8665-3993f8eabb18.png)

From an [industry page](https://www.marsh.com/us/services/analytics.html):
![image](https://cloud.githubusercontent.com/assets/8258720/8991946/bcfca42e-36c9-11e5-83ea-50840a09296b.png)

Related tickets:
https://github.com/DrewAllen88/Enhancements/issues/34, https://github.com/DrewAllen88/Enhancements/issues/24

**Comment by abhishek-a** [comment]
hi Drew, Please provide a Promo Carosuel snapshot and a live site or stage en link to see it.

**Comment by DrewAllen88** [comment]
@abhishek-a I have added some screenshots and links for you.

**Comment by DrewAllen88** [comment]
Are we able to prepopulate the fields that pull from the source? Like the Over-ride Title and Over-ride Description fields? Then the author can see and change the text right there if they wish.

We would also like to consider indicating to the user whether they have gone over the "character limit" that we are indicating. Some sort of visual indication.

![image](https://cloud.githubusercontent.com/assets/8258720/9137186/0f4aae94-3cea-11e5-9a85-6f75b40848e6.png)

@abhishek-a

**Comment by ABHINAV-CHANSARKAR** [comment]
Character limit to over-ride Content type has not been specified. Have calculated and found it to be 65 for one line of content including spaces. Please suggest if a change is required.

**Comment by monalishah** [comment]
Dev Complete.

**Comment by DrewAllen88** [comment]
UAT complete.

The items under the component edit have not yet been taken care of. The top two tabs should say:
- Promo Source --> Dynamic Authoring
- Promo --> Manual Authoring

![image](https://cloud.githubusercontent.com/assets/8258720/9580698/ee0433ee-4fc8-11e5-9f78-f7092e23d681.png)

Also on right click of the component on the page we need to update the header to indicate the component in question. Here it is a Promo Carousel but it doesn't say anything. Should specify, much like the Feature Story Carousel does:

![image](https://cloud.githubusercontent.com/assets/8258720/9580755/4c02beac-4fc9-11e5-91b7-326479443922.png)

A validation error message displays for the error thrown when the Over-ride Description field is past the character limit but does not indicate that in the message.

![image](https://cloud.githubusercontent.com/assets/8258720/9580927/4ec478f0-4fca-11e5-9618-f51dfa9bc105.png)

On the Promo tab where a Promo Carousel item is manually authored, there is no character limit applied to the Description field. The value should be the same as the Over-ride Description field.

**Comment by DrewAllen88** [comment]
All good.
