### ISSUE TITLE
RIMS Canada Site Launch

### ISSUE THREAD

**Issue by DrewAllen88** [DrewAllen88/Enhancements#69]
Site launch on August 21st.

Tasks to complete for the BAU team.

**Comment by markharle** [comment]
Additional comments:
Goal is to be ready for PROD UAT 8/19 
Here is the URL to the pre-release site (content not updated as of today):
http://author-prod2.www.marshinc.net/cf#/content/marsh/microsites/rimscanada/en/home.html
I will ask Abhishek to have this ready for PROD UAT on 8/19, and will send him the Accenture-created micros-site launch document in case he doesn't have a copy. (Marsh com New Microsites Approach.doc)
