### ISSUE TITLE
Right Rail Component Widths

### ISSUE THREAD

**Issue by DrewAllen88** [DrewAllen88/Enhancements#70]
All RR components need to be consolidated for widths, they need to consistently fit across all templates.

**Comment by timproDev** [comment]
segment-industry-services is the standard

**Comment by timproDev** [comment]
Requires class name edits in the template which I imagine would be done by the BAU team.

DOM Class Name Change | Product Solution Page
DOM class name change | press release detail page
DOM class name change | campaign page - on hold - need design input
CSS change | .campaign-wrap aside : campaign page - on hold - need design input
CSS change | .article-wrap aside : article page
CSS change | .article-wrap aside : article login page
CSS change | .who-we-are-wrap aside : about us recruiting who we are page

**Comment by DrewAllen88** [comment]
This going to make the SEPT 4 release? @timproDev

**Comment by timproDev** [comment]
@DrewAllen88 I am shooting for it. This would mean it would be included in this Friday's FED deliverable.

**Comment by DrewAllen88** [comment]
@timproDev detail the documentation for BAU.

**Comment by HarshitKhandelwal** [comment]
HTML class changed for product solution and press release detail page. Awaiting FED update for remaining pages.
