### ISSUE TITLE
Accordion White Space Issue

### ISSUE THREAD

**Issue by DrewAllen88** [DrewAllen88/Enhancements#80]
White space being created above accordion and accordion items when authored.
[Example link](http://author-prod2.www.marshinc.net/cf#/content/marsh/europe/uk/en/about-marsh/about-us.html?cq_ck=1439485633086)

**Comment by HarshitKhandelwal** [comment]
Is this the ticket raised for the issue raised by Will last week over mail?

**Comment by DrewAllen88** [comment]
Yes it is @HarshitKhandelwal

**Comment by DrewAllen88** [comment]
UAT Complete.
