### ISSUE TITLE
Breadcrumb Author Image

### ISSUE THREAD

**Issue by DrewAllen88** [DrewAllen88/Enhancements#85]
When you author the breadcrumb component it requires the Client Hub link to be authored. This should not be required, as in some cases there is no site login.

**Comment by HarshitKhandelwal** [comment]
Dev completed. To be included in Sept 4 release.

**Comment by joyjamir** [comment]
@DrewAllen88 Is this included in the 9/4 release?

**Comment by DrewAllen88** [comment]
@joyjamir Yes it is.

**Comment by DrewAllen88** [comment]
Done.
